name: Testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: testing-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  codeql:
    name: Security and Quality
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install dependencies
      run: python -m pip install -e .

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python
        queries: security-and-quality
        source-root: .

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  flake8:
    name: Flake8
    uses: OpenTTD/actions/.github/workflows/rw-py-flake8.yml@v5
    with:
      python-path: openttd_protocol

  black:
    name: Black
    uses: OpenTTD/actions/.github/workflows/rw-py-black.yml@v5
    with:
      python-version: 3.8
      python-path: openttd_protocol

  pytest:
    name: pytest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install pytest
      run: |
        python -m pip install -r requirements.test

    - name: Run pytest
      run: |
        PYTHONPATH=. pytest

  annotation_check:
    name: Annotation Check
    needs:
    - flake8
    - black
    - pytest
    # not codeql, as that reports its own status

    uses: OpenTTD/actions/.github/workflows/rw-annotation-check.yml@v5
